version: '3'

services:
  doc-extractor:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
